Traceback (most recent call last):
  File "tests/Python_Errors/StopIteration.py", line 4, in <module>
    next(it)
StopIteration

